Started implementing CSP Nonce (#30)
* Started implementing CSP Nonce

* Removed nonce definition

* Removed Helpers

* Changed to update header to include nonce only if called by the TagHelper

* Reworked with service

* Removed as unrequired

* Changed to check context

* Fixed incorrect key

* Reversed check

* Added ability to output data-attribute nonce

* Removed unused class

* Removed unused interface

* Corrected check

* Updated readme

* Moved to constant

* Updated more places to use constants

* Branch update and some code changes

* Code changes reordered CSP directives

* code clean up and testing fix

* Build fixes

* Build pipeline permissions

* Test reporter doesnt support external PRS so need to split into two actions

* fix yaml formatting

* Fix test run report uploading

* Fix report yaml

* Fixing reporting

* Fixing reporting

* Update step versions

---------

Co-authored-by: Matthew Wise <6782865+Matthew-Wise@users.noreply.github.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -14,22 +14,19 @@ jobs:
   build:
     env:
       BUILD_CONFIG: "Release"
+      LogFileName: "test-results.trx"
       PROJECT: "./src/Umbraco.Community.CSPManager/Umbraco.Community.CSPManager.csproj"
       TESTPROJECT: "./src/Umbraco.Community.CSPManager.Tests/Umbraco.Community.CSPManager.Tests.csproj"
+      TESTLOGPATH: "./src/Umbraco.Community.CSPManager.Tests/TestResults/"
       BUILD_VERSION: ${{ github.event.release.tag_name || '0.0.0' }}
 
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v3
-
-      - name: Setup NuGet
-        uses: NuGet/setup-nuget@v1
-        with:
-          nuget-version: "6.x"
+      - uses: actions/checkout@v4
 
       - name: Setup .NET
-        uses: actions/setup-dotnet@v3
+        uses: actions/setup-dotnet@v4
         with:
           dotnet-version: |
             6.x
@@ -48,17 +45,14 @@ jobs:
         run: dotnet build $TESTPROJECT -c $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore
 
       - name: Run tests
-        run: dotnet test $TESTPROJECT -c  $BUILD_CONFIG --no-build --verbosity normal --filter "Category!=LongRunning" --logger "trx;LogFileName=test-results.trx"
-
-      - name: Test Report
-        uses: dorny/test-reporter@v1
-        if: always()
+        run: dotnet test $TESTPROJECT -c  $BUILD_CONFIG --no-build --verbosity normal --filter "Category!=LongRunning" --logger "trx;LogFileName=$LogFileName"
+        
+      - uses: actions/upload-artifact@v4  # upload test results
+        if: success() || failure()        # run this step even if previous step failed
         with:
-            name: DotNET Tests
-            path: "**/test-results.trx"                            
-            reporter: dotnet-trx
-            fail-on-error: true
-  
+          name: test-results
+          path: "${{env.TESTLOGPATH}}${{env.LogFileName}}"
+
       - name: Publish
         if: github.event_name == 'release'
         run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
